server:
  port: 8088

secure:
  ignored:
    urls: #경로 화이트 리스트
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /api/post/**
      - /api/stat/**



---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/game_service?useSSL=false&useUnicode=yes&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#riot open-api data
open-api:
  riot:
    api-key: RGAPI-1d5f1be9-ae39-4cbb-a7b3-2dfd3ca4f169
